goodsApp/urls.py
from django.urls import path
from .views import *

app_name = 'goodsApp'

urlpatterns = [
    path('', PartnerView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
    path('products/', get_products, name='products'),
    path('products/<int:cat_id>', get_category, name='get_category'),
    path('products_detail/<int:prod_id>', get_detail, name='get_detail'),
    path('ajax/<sort_by>', sorting, name='sorting'),

    path('blog/', get_blog, name="get_blog"),
    path('blog/<int:id>', get_blog_detail, name="get_blog_detail"),
    path('event/', create_event, name="create_event"),
    path('event/<int:id>', get_event_detail, name="get_event_detail"),
    path('event/<str:month>', get_event_archieve, name="get_event_archieve"),
    path('event/category/<str:slug>', get_category_event, name='get_category_event'),
    # path('search/', search_products, name='search_results'),
    path('blog/', get_blog, name="get_blog"),
    path('blog/<int:id>', get_blog_detail, name="get_blog_detail"),
    path('blog/<str:month>', get_archieve, name="get_archieve"),
    path('blog/category/<str:cat_id>', get_category_blog, name='get_category_blog'),
    path("contact/", contact, name="contact"),

]

produceAz/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    # path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    # path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('admin/', admin.site.urls),
    path('',include('goodsApp.urls',namespace='goodsApp'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goodsApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255, blank=False, null=True)
    slug =  models.SlugField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)


class Products(models.Model):
    name = models.CharField(max_length=255, blank=False, null=True)
    image = models.ImageField(upload_to='categories')
    price = models.FloatField()
    contact = models.CharField(max_length=255, blank=False, null=True)
    email = models.EmailField(max_length=60, blank=False, null=True)
    made_in = models.CharField(max_length=255, blank=False, null=True)
    url = models.CharField(max_length=255, blank=False, null=True)
    description = models.TextField(blank=False, null=True)
    add_info = models.CharField(max_length=255, blank=False, null=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='products', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class AboutPage(models.Model):
    title = models.CharField(max_length=255,blank=True,null=False)
    text = models.CharField(max_length=255,blank=True,null=False)
    background_img = models.ImageField(max_length=255,blank=True,null=False)
    image = models.ImageField(upload_to='aboutpage_images')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)




class Partner(models.Model): 
    partner_name = models.CharField(max_length=255,blank=True,null=False)
    partner_image = models.ImageField(upload_to='partner_image')
    partner_des = models.CharField(max_length=255,blank=True,null=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class NavLink(models.Model):
    title = models.CharField(max_length=255,blank=False,null=False) 
    url = models.CharField(max_length=255,blank=True)
    active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title



# class Post(models.Model):
#     title = models.CharField(max_length=255, null = True)
#     description = models.CharField(max_length=255, null = True, blank = True)
#     text = models.TextField(null = True, blank = True)
#     created_at = models.DateTimeField(auto_now_add=True)
#     image = models.ImageField(upload_to = 'blog_images')
#     author = models.ForeignKey(User, on_delete=models.CASCADE)
#
#
#     def __str__(self):
#         return self.title or self.id



class Event(models.Model):
    title = models.CharField(max_length=255, null = True)
    description = models.CharField(max_length=255, null = True, blank = True)
    text = models.TextField(null = True, blank = True)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to = 'blog_images')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    start_date = models.DateField(null = True, blank = True)
    end_date = models.DateField(null = True, blank = True)
    test_date = models.DateField(null = True, blank = True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, null=True,blank=True)

    def __str__(self):
        return self.title or self.id

class Post(models.Model):
    title = models.CharField(max_length=255, null = True)
    description = models.CharField(max_length=255, null = True, blank = True)
    text = models.TextField(null = True, blank = True)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to = 'blog_images')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    test_date = models.DateField(null = True, blank = True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, null=True,blank=True)


    def __str__(self):
        return self.title or self.id


class HeaderModel(models.Model):
    title = models.CharField(max_length=244)
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.title


class BackgroundImage(models.Model):
    header = models.ForeignKey('HeaderModel', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='background')

    def __str__(self):
        return self.header.title

class ContactUs(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone_number = models.CharField(max_length=200)
    message = models.TextField()

    def __str__(self):
        return f"{self.name}"

goodsApp/forms.py
from django import forms
from .models import ContactUs

class ContactForm(forms.ModelForm):

    class Meta:
        model = ContactUs
        fields = ["name", "email",
                  "phone_number", "message"]

goodsApp/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, CreateView, ListView, DetailView
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from django.views.generic.edit import FormMixin, UpdateView
from django.contrib.auth.models import User
from goodsApp.forms import *
from django.db.models import Q
from .models import *
from django.http import HttpResponse, JsonResponse
import calendar


def category_filter(name):
    category = Category.objects.all()
    result = []
    for i in category:
        events = eval(f'i.{name}_set.all()')
        # events = i.event_set.all()
        if events:
            result.append(i)
    return result


class AboutView(TemplateView):
    template_name = 'about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["content"] = AboutPage.objects.last()
        return context


class PartnerView(ListView):
    model = Partner
    context_object_name = 'partners'
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["last_products"] = Products.objects.order_by('-created_at')[0:8]
        context["blogs"] = Post.objects.order_by('?')[0:3]
        context["products"] = Products.objects.order_by('?')[0:3]
        try:
            context['backgrounds'] = HeaderModel.objects.all().first().backgroundimage_set.all()
            context['header'] = HeaderModel.objects.all()[0]
        except:
            pass

        context['randoms'] = Products.objects.all()[0:7]
        context['events'] = Event.objects.all()[0:4]
        print(context)
        return context


def get_blog(request):
    post_list = Post.objects.all()

    if request.method == 'POST':
        search = request.POST.get('search')
        post_list = Post.objects.filter(
            Q(title__icontains=search) | Q(text__icontains=search) | Q(description__icontains=search))

    paginator = Paginator(post_list, 2)

    page = request.GET.get('page')
    posts = paginator.get_page(page)

    context = {
        'posts': posts
    }
    return render(request, 'blog.html', context)


def get_blog_detail(request, id):
    post = Post.objects.get(id=id)

    context = {
        'post': post
    }
    return render(request, 'blog-detail.html', context)


# ----------------------------------------------------------------------------------------------------------

# -----------------------------------------------------------API for jquery drop down------------------------------

def sorting(request, sort_by):
    if request.method == 'POST':
        cat_id = request.POST.get('cat_id')
        if cat_id:
            products = Products.objects.filter(category__id=cat_id).order_by(sort_by)
        else:
            products = Products.objects.order_by(sort_by)
        product_list = list(products.values('id', 'name', 'price', 'image'))

        return JsonResponse(product_list, safe=False)

    # -----------------------------------------------------------------------------------------------------------------


# **********************************************Products***************************************************
def get_products(request):
    product_list = Products.objects.all()
    if request.is_ajax():
        result = []
        for i in product_list:
            obj = {'name': i.name}
            result.append(obj)

        return JsonResponse({
            'name': result
        })

    if request.method == 'POST':
        query = request.POST.get('q')
        product_list = Products.objects.filter(
            Q(name__icontains=query) | Q(category__name__icontains=query) | Q(price__icontains=query) | Q(
                created_at__icontains=query))

    categories = Category.objects.all()

    paginator = Paginator(product_list, 6)
    page = request.GET.get('page')
    products = paginator.get_page(page)

    len_product = product_list.count()
    page_num = products.number
    start = (page_num - 1) * 6 + 1
    end = 6 * page_num
    if end > len_product:
        end = len_product

    context = {
        'categories': categories,
        'products': products,
        'len_product': len_product,
        'start': start,
        'end': end,
    }

    return render(request, 'product.html', context)


# ---------------------------------------------------------------Categories----------------------------------------
def get_category(request, cat_id):
    categories = Category.objects.all()
    product_list = Products.objects.filter(category__id=cat_id)

    if request.method == 'POST':  # for searching field in categories
        query = request.POST.get('q')
        product_list = Products.objects.filter(
            Q(name__icontains=query) | Q(category__name__icontains=query) | Q(price__icontains=query) | Q(
                created_at__icontains=query))

    paginator = Paginator(product_list, 6)
    page = request.GET.get('page')
    products = paginator.get_page(page)

    len_product = product_list.count()
    page_num = products.number
    start = (page_num - 1) * 6 + 1
    end = 6 * page_num
    if end > len_product:
        end = len_product

    context = {
        'cat_id': cat_id,
        'categories': categories,
        'products': products,
        'len_product': len_product,
        'start': start,
        'end': end,
    }

    return render(request, 'product.html', context)


# ---------------------------------------------------------Detail Of Product ---------------------------------------
def get_detail(request, prod_id):
    product = Products.objects.get(id=prod_id)
    context = {
        'product': product,
    }
    return render(request, 'product-detail.html', context)


# ------------------------------------------------------------------------------------------------------------------

def create_event(request):
    event_list = Event.objects.all()

    if 'search'  in  request.GET:
        search = request.GET.get('search')
        event_list = Event.objects.filter(
            Q(title__icontains=search) | Q(text__icontains=search) | Q(description__icontains=search))

    paginator = Paginator(event_list, 2)

    first_count = Event.objects.filter(end_date__month=1).count()
    second_count = Event.objects.filter(end_date__month=12).count()
    third_count = Event.objects.filter(end_date__month=11).count()

    page = request.GET.get('page')
    events = paginator.get_page(page)

    context = {
        'events': events,
        'first_count': first_count,
        'second_count': second_count,
        'third_count': third_count,
        'categories': category_filter('event')
    }
    return render(request, 'event2.html', context)


def get_event_detail(request, id):
    event = Event.objects.get(id=id)

    context = {
        'event': event,
        'category': category_filter('event'),
    }
    return render(request, 'event-detail.html', context)


def get_event_archieve(request, month):
    months = [
        'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August',
        'September', 'October', 'November', 'December'
    ]
    index = months.index(month) + 1
    event_list = Event.objects.filter(end_date__month=index)

    if 'search' in  request.GET:
        search = request.GET.get('search')
        event_list = Event.objects.filter(
            Q(title__icontains=search) | Q(text__icontains=search) | Q(description__icontains=search))

    first_count = Event.objects.filter(end_date__month=1).count()
    second_count = Event.objects.filter(end_date__month=12).count()
    third_count = Event.objects.filter(end_date__month=11).count()

    paginator = Paginator(event_list, 2)

    page = request.GET.get('page')
    events = paginator.get_page(page)

    context = {
        'events': events,
        'first_count': first_count,
        'second_count': second_count,
        'third_count': third_count,
        'categories': category_filter('event'),

    }
    return render(request, 'event2.html', context)


def get_category_event(request, slug):
    categories = Category.objects.all()
    event_list = Event.objects.filter(category__slug=slug)

    if 'search' in  request.GET:  # for searching field in categories
        query = request.GET.get('search')
        event_list = Event.objects.filter(
            Q(title__icontains=query) | Q(category__name__icontains=query) | Q(description__contains=query) | Q(
                created_at__icontains=query))

    paginator = Paginator(event_list, 2)
    page = request.GET.get('page')
    products = paginator.get_page(page)

    len_product = event_list.count()
    page_num = products.number
    start = (page_num - 1) * 6 + 1
    end = 6 * page_num
    if end > len_product:
        end = len_product
    # paginator = Paginator(event_list, 2)

    first_count = Event.objects.filter(end_date__month=1).count()
    second_count = Event.objects.filter(end_date__month=12).count()
    third_count = Event.objects.filter(end_date__month=11).count()

    context = {

        'categories': category_filter('event'),
        'events': products,
        'first_count': first_count,
        'second_count': second_count,
        'third_count': third_count,


    }

    return render(request, 'event2.html', context)


# blogs
def get_blog(request):
    post_list = Post.objects.all()

    if 'search' in request.GET:
        search = request.GET.get('search')
        post_list = Post.objects.filter(
            Q(title__icontains=search) | Q(text__icontains=search) | Q(description__icontains=search))

    paginator = Paginator(post_list, 2)

    first_count = Post.objects.filter(test_date__year=2020, test_date__month=1).count()
    second_count = Post.objects.filter(test_date__year=2019, test_date__month=11).count()

goodsApp/templates/about.html
{% extends 'base/base.html' %}
{% load static %}

	<!-- Title Page -->
	{% block content %}
	
	<section class="bg-title-page p-t-40 p-b-50 flex-col-c-m" style="background-image: url({{content.background_img.url}})"; "width:1920px"; "height:236px" >
		<h2 class="l-text2 t-center">
			About
		</h2>
	</section>

	<!-- content page -->
	<section class="bgwhite p-t-66 p-b-38">
		<div class="container">
			<div class="row">
				<div class="col-md-4 p-b-30">
					<div class="hov-img-zoom">
						<img src="{{content.image.url}}"; style= "height:400px" alt="IMG-ABOUT">
					</div>
				</div>

				<div class="col-md-8 p-b-30">
					<h3 class="m-text26 p-t-15 p-b-16">
						{{content.title}}
					</h3>

					<p class="p-b-28">
						{{content.text}}
					</p>

					<div class="bo13 p-l-29 m-l-9 p-b-10">
						{% comment %} <p class="p-b-11">
							Creativity is just connecting things. When you ask creative people how they did something, they feel a little guilty because they didn't really do it, they just saw something. It seemed obvious to them after a while.
						</p> {% endcomment %}

						<span class="s-text7">
							- Steve Job’s
						</span>
					</div>
				</div>
			</div>
		</div>
	</section>

	{% block scripts %}
	<script type="text/javascript">
		$(".selection-1").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect1')
		});

		$(".selection-2").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect2')
		});
	</script>
	{% endblock scripts %}

{% endblock content %}

	
	
<!--===============================================================================================-->


goodsApp/templates/blog-detail.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}



	<!-- breadcrumb -->
	<div class="bread-crumb bgwhite flex-w p-l-52 p-r-15 p-t-30 p-l-15-sm">
		<a href="index.html" class="s-text16">
			Home
			<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
		</a>

		<a href="blog.html" class="s-text16">
			Blog
			<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
		</a>

		<span class="s-text17">
			{{ post.title }}
		</span>
	</div>

	<!-- content page -->
	<section class="bgwhite p-t-60 p-b-25">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-lg-9 p-b-80">
					<div class="p-r-50 p-r-0-lg">
						<div class="p-b-40">
							<div class="blog-detail-img wrap-pic-w">
								<img src="{{ post.image.url }}" alt="IMG-BLOG">
							</div>

							<div class="blog-detail-txt p-t-33">
								<h4 class="p-b-11 m-text24">
									{{ post.title }}
								</h4>

								<div class="s-text8 flex-w flex-m p-b-21">
									<span>
										{{ post.author }}
										<span class="m-l-3 m-r-6">|</span>
									</span>

									<span>
										{{ post.created_at }}
										<span class="m-l-3 m-r-6">|</span>
									</span>

									<span>
										Cooking, Food
										<span class="m-l-3 m-r-6">|</span>
									</span>

									<span>
										8 Comments
									</span>
								</div>

								<p class="p-b-25">
									{{ post.description }}
								</p>

								<p class="p-b-25">
									{{ post.text }}
								</p>
							</div>

							<div class="flex-m flex-w p-t-20">
							</div>
						</div>

					</div>
				</div>


				</div>
			</div>
		</div>
	</section>


{% endblock %}

goodsApp/templates/event-detail.html
{% extends 'base/base.html' %}

{% block content %}



    <!-- breadcrumb -->
    <div class="bread-crumb bgwhite flex-w p-l-52 p-r-15 p-t-30 p-l-15-sm">
        <a href="{% url 'goodsApp:index' %}" class="s-text16">
            Home
            <i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
        </a>

        <a href="{% url 'goodsApp:create_event' %}" class="s-text16">
            Event
            <i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
        </a>

        <span class="s-text17">
			{{ event.title }}
		</span>


    </div>

    <!-- content page -->
    <section class="bgwhite p-t-60 p-b-25">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-9 p-b-80">
                    <div class="p-r-50 p-r-0-lg">
                        <div class="p-b-40">
                            <div class="blog-detail-img wrap-pic-w">
                                <img src="{{ event.image.url }}" alt="IMG-BLOG">
                            </div>

                            <div class="blog-detail-txt p-t-33">
                                <h4 class="p-b-11 m-text24">
                                    {{ event.title }}
                                </h4>

                                <div class="s-text8 flex-w flex-m p-b-21">
									<span>
										{{ event.author }}
										<span class="m-l-3 m-r-6">|</span>
									</span>

                                    <span>
										{{ event.created_at }}
										<span class="m-l-3 m-r-6">|</span>
									</span>

                                    <span>
										{{ event.start_date }} - {{ event.end_date }}
										<span class="m-l-3 m-r-6">|</span>
									</span>

                                    <span>
										Cooking, Food
										<span class="m-l-3 m-r-6">|</span>
									</span>

                                    <span>
										8 Comments
									</span>
                                </div>

                                <p class="p-b-25">
                                    {{ event.description }}
                                </p>

                                <p class="p-b-25">
                                    {{ event.text }}
                                </p>
                            </div>

                            <div class="flex-m flex-w p-t-20">
                            </div>
                        </div>

                    </div>
                </div>


            </div>
        </div>
        </div>
    </section>


{% endblock %}

goodsApp/templates/event2.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

    <!-- Title Page -->
    <section class="bg-title-page p-t-40 p-b-50 flex-col-c-m"
             style="background-image: url({% static 'images/blog-head.jpeg' %});">
        <h2 class="l-text2 t-center">
            Blog
        </h2>
    </section>

    <!-- content page -->
    <section class="bgwhite p-t-60">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-9 p-b-75">
                    <div class="p-r-50 p-r-0-lg">
                        {% for post in events %}
                            <div class="item-blog p-b-80">
                                <a href="{% url 'goodsApp:get_blog_detail' post.id %}"
                                   class="item-blog-img pos-relative dis-block hov-img-zoom">
                                    <img src="{{ post.image.url }}"  alt="IMG-BLOG">
                                    <span class="item-blog-date dis-block flex-c-m pos1 size17 bg4 s-text1">
									{{ post.created_at }}
								</span>
                                </a>

                                <div class="item-blog-txt p-t-33">
                                    <h4 class="p-b-11">
                                        <a href="{% url 'goodsApp:get_blog_detail' post.id %}" class="m-text24">
                                            {{ post.title }}
                                        </a>
                                    </h4>

                                    <div class="s-text8 flex-w flex-m p-b-21">
									<span>
										{{ post.author }}
										<span class="m-l-3 m-r-6">|</span>
									</span>

                                        <span>
										Cooking, Food
										<span class="m-l-3 m-r-6">|</span>
									</span>

                                    </div>

                                    <p class="p-b-12">
                                        {{ post.description }}
                                    </p>

                                    <a href="{% url 'goodsApp:get_event_detail' post.id %}" class="s-text20">
                                        Continue Reading
                                        <i class="fa fa-long-arrow-right m-l-8" aria-hidden="true"></i>
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>

                    <!-- Pagination -->
                {% if posts %}
                    <div class="pagination flex-m flex-w p-r-50">
                        {% if posts.has_previous %}
                            <a href="?page=1" class="item-pagination flex-c-m trans-0-4"><<</a>
                            <a href="?page={{ posts.previous_page_number }}"
                               class="item-pagination flex-c-m trans-0-4">{{ posts.previous_page_number }}</a>
                        {% endif %}

                        <span class="current">
							<a href="?page={{ posts.number }}"
                               class="item-pagination flex-c-m trans-0-4 active-pagination">{{ posts.number }}</a>
						</span>

                        {% if posts.has_next %}
                            <a href="?page={{ posts.next_page_number }}"
                               class="item-pagination flex-c-m trans-0-4">{{ posts.next_page_number }}</a>
                            <a href="?page={{ posts.paginator.num_pages }}" class="item-pagination flex-c-m trans-0-4">>></a>
                        {% endif %}
                    </div>
               {% endif %}
                </div>

                <div class="col-md-4 col-lg-3 p-b-75">
                    <div class="rightbar">
                        <!-- Search -->
                        <form method="GET">
{#                            {% csrf_token %}#}
                            <div class="pos-relative bo11 of-hidden">
                                <input class="s-text7 size16 p-l-23 p-r-50" type="text" name="search"
                                       placeholder="Search">

                                <button type="submit" class="flex-c-m size5 ab-r-m color1 color0-hov trans-0-4">
                                    <i class="fs-13 fa fa-search" aria-hidden="true"></i>
                                </button>
                            </div>
                        </form>
                        <br>
                        <br>
                        <br>
                        <!-- Categories -->
                        <h4 class="m-text23 p-t-56 p-b-34">
                            Categories
                        </h4>

                        <ul>
                            <li class="p-t-6 p-b-8 bo6">
                                <a href="{% url 'goodsApp:create_event' %}" class="s-text13 p-t-5 p-b-5">
                                    All
                                </a>
                            </li>
                            {% for field in categories %}
                                <li class="p-t-6 p-b-8 bo7">
                                    <a href="{% url 'goodsApp:get_category_event' field.slug %}"
                                       class="s-text13 p-t-5 p-b-5">
                                        {{ field.name }}
                                    </a>
                                </li>

                            {% endfor %}

                        </ul>
                        <!-- Featured Products -->
                        <!-- Archive -->
                        <h4 class="m-text23 p-t-50 p-b-16">
                            Archive
                        </h4>

                        <ul>
                            <li class="flex-sb-m">
                                <a href="{% url 'goodsApp:get_event_archieve' 'January' %}" class="s-text13 p-t-5 p-b-5">
                                    January 2020
                                </a>

                                <span class="s-text13">
									({{ first_count }})
								</span>
                            </li>

                            <li class="flex-sb-m">
                                <a href="{% url 'goodsApp:get_event_archieve' 'December' %}" class="s-text13 p-t-5 p-b-5">
                                    December 2019
                                </a>

                                <span class="s-text13">
									({{ second_count }})
								</span>
                            </li>

                            <li class="flex-sb-m">
                                <a href="{% url 'goodsApp:get_event_archieve' 'November' %}" class="s-text13 p-t-5 p-b-5">
                                    November 2019
                                </a>

                                <span class="s-text13">
									({{ third_count }})
								</span>
                            </li>

                            {% comment %} <li class="flex-sb-m">
								<a href="#" class="s-text13 p-t-5 p-b-5">
									April  2018
								</a>

								<span class="s-text13">
									(35)
								</span>
							</li>

							<li class="flex-sb-m">
								<a href="#" class="s-text13 p-t-5 p-b-5">
									March 2018
								</a>

								<span class="s-text13">
									(22)
								</span>
							</li>

							<li class="flex-sb-m">
								<a href="#" class="s-text13 p-t-5 p-b-5">
									February 2018
								</a>

								<span class="s-text13">
									(32)
								</span>
							</li>

							<li class="flex-sb-m">
								<a href="#" class="s-text13 p-t-5 p-b-5">
									January 2018
								</a>

								<span class="s-text13">
									(21)
								</span>
							</li>

							<li class="flex-sb-m">
								<a href="#" class="s-text13 p-t-5 p-b-5">
									December 2017
								</a>

								<span class="s-text13">
									(26)
								</span>
							</li> {% endcomment %}
                        </ul>

                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>

{% endblock %}